import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :signcraft, SigncraftWeb.Endpoint,
  url: [host: "your-domain.com", port: 443, scheme: "https"],
  check_origin: [
    "https://peytonjpope.com",
    "https://signcraft.fly.dev"  # Keep your Fly.io URL as backup
  ]
# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Signcraft.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
